sudo: required
services:
    - docker

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - docker build -t tejozarkar/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:3000 tejozarkar/docker-angular npm run test
