sudo: required
services:
    - docker

dist: xenial
addons:
    chrome: stable

before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - docker build -t tejozarkar/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:3000 tejozarkar/docker-angular npm run test
