sudo: required
services:
    - docker

dist: xenial
addons:
    chrome: stable

before_install:
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - docker build -t tejozarkar/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:3000 tejozarkar/docker-angular npm run test
