dist: trusty
sudo: required
services:
    - docker
addons:
    chrome: stable # have Travis install chrome stable.

before_install:
    - docker build -t tejozarkar/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:3000 tejozarkar/docker-angular npm run test
