sudo: required
services:
    - docker
dist: trusty
addons:
    apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start &
    - sleep 3
    - docker build -t tejozarkar/docker-angular -f Dockerfile.dev . 

script:
    - docker run -e CI=true -p 80:3000 tejozarkar/docker-angular npm run test
